<Project Sdk="MSTest.Sdk/3.6.1">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Biz.Bizadm.Lucene.Net.Extensions.RuntimeTests.Unix</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lucene.Net.Extensions.Runtime.Unix\Lucene.Net.Extensions.Runtime.Unix.csproj" />
  </ItemGroup>
</Project>
